import pyautogui
import time
import pydirectinput
pyautogui.press("win")
time.sleep(5)
#pyautogui.press("r")
#pyautogui.press("o")
#pyautogui.press("b")
#pyautogui.press('l')
#pyautogui.press("o")
#pyautogui.press("x")
pyautogui.write("roblox")
time.sleep(3)
pyautogui.doubleClick(300,200)
time.sleep(18)
pydirectinput.rightClick(756,380)
time.sleep(1)
pydirectinput.rightClick(756,380)
time.sleep(2)
pydirectinput.click(681,316)
time.sleep(3)
pydirectinput.click(681,316)
time.sleep(3)
pyautogui.write("nayuara10")
pydirectinput.click(692,459)
time.sleep(3)
pydirectinput.click(692,459)